version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
  ingestion:
    build: ./ingestion
    env_file: common.env
    environment:
      - VIRTUAL_PROTO=fastcgi
      - VIRTUAL_ROOT=/var/www/html
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:alpine
    restart: always
  delivery:
    build: ./delivery
    env_file: common.env
    depends_on:
      - redis
    restart: always
