
version: "3"

services:
  ingestion:
    build: ./ingestion
    ports:
      - "80:80"
      # - "443:443"
    env_file: common.env
    depends_on:
      - redis
  redis:
    image: redis:alpine
  delivery:
    build: ./delivery
    env_file: common.env
    depends_on:
      - redis
    restart: on-failure
